### PR TITLE
Added alot of commits

### PR DESCRIPTION
**Pull request by pilppe**
Hi, im EdenStudio from the forums

1# I added a snowing javascript that should be enabled only when its Christmas
2# added snowflake.svg
3# updated snowsrc
4# added comments and modified the script
5# added internet explorer detection that whines if your IE is under 8 to fix any future compatibility issues @ index.html
6# added ie.html that the user gets redirected to if IE > 8
7# Updated javascript with the right redirect

### CODE REVIEW

**Comment by andrewjcole** [comment]
We'll see what the group's opinion is on this. I assigned Cheese-Eater so he can see it.

**Comment by pilppe** [comment]
Thank you. I would love to be a contributor too.

**Comment by The-QullzToxic** [comment]
You could add a bit about IE, maybe newer versions, and allow them on the site and make it display something like this: Your using Internet Explorer, OpenSprites does not recommend using Internet Explorer, upgrade to a new browser like Firefox! You`ll find its a lot quicker too!

**Comment by pilppe** [comment]
That would be cool. I could add "Continue to the site or Download Chrome"

**Comment by The-QullzToxic** [comment]
No... Not Chrome... Not da google web browser dat tracks you and stuffs D:

**Comment by The-Cheese-Eater** [comment]
Great, thanks for your work! If you'd like to become a developer, please ask on the thread so I can keep account of everything. Thank you. :smile:

**Comment by andrewjcole** [comment]
@The-QullzToxic Chromium... :+1:

**Comment by Firedrake969** [comment]
Let's not force the user to use anything...
(unless they're using IE :P)

**Comment by andrewjcole** [comment]
Changed.

**Comment by Firedrake969** [comment]
changed what?

**Comment by The-Cheese-Eater** [comment]
He changed the link to Chrome to the browser choices site. Anyone using IE is on a sinking ship, the only thing it's good for now is checking Windows Updates on old XP. :P I liked Chrome's simple and modern design, but the fact that Google made it, scared me into uninstalling it. Firefox works OK, but HTML5 video playback is the most terrible I've seen, ever.

**Comment by pilppe** [comment]
I use Chromium myself, way better.

**Comment by Firedrake969** [comment]
@The-Cheese-Eater you're wrong - it's amazing at downloading Chrome!  xD

**Comment by The-Cheese-Eater** [comment]
xD

**Pull request merged**
