### PR TITLE
RSS Feed For The Blog

### PR DESCRIPTION
**Pull request by QuillzLouis**
I setup an rss xml, I just need to setup feedburner once this has been
pushed.

### CODE REVIEW

**Comment by Firedrake969** [comment]
I would suggest some sort of automatic feed generator instead of having to manually update the feed as well as the blog.

**Comment by QuillzLouis** [comment]
There isn't any, I looked

**Comment by Firedrake969** [comment]
It doesn't have to be premade.

**Comment by QuillzLouis** [comment]
ik

**Comment by QuillzLouis** [comment]
There is no database on the blog...

**Comment by Firedrake969** [comment]
I don't think that RSS feeds should be manually updated.  Closing for now.

**Comment by liam4** [comment]
(add tags enhancement, feature, idea?)

**Pull request closed without merging**
