### PR TITLE
Refactoring of many things

### PR DESCRIPTION
**Pull request by robinp7720**
Trust me. This is better.
Probably still a few mistakes in the re-factoring.
You guys have really gotta give contributes a way to setup the database

### CODE REVIEW

**Comment by liam4** [comment]
No - why [delete](https://github.com/robinp7720/OpenSprites/commit/d23ef6f9c49c05824180f805053166dad164eeee) `OpenSprites is Illuminati.mp3`? :(

**Comment by The-Cheese-Eater** [comment]
Lets not be hasty now. ;)

**Comment by robinp7720** [comment]
@The-Cheese-Eater Thanks.
Overall, this repo is really just cluttered and unorganized. (Sorry about admitting this)

This is really just one of my first PR's. I plan on creating separate classes for all functions for database access and user functions. Probably half the size of the repo while doing so. 

@liam4 So.. Just commit the file back yourself..

**Comment by Firedrake969** [comment]
"only experienced php programmer"
hey @MegaApuTurkUltra want to have some fun here :P

**Comment by robinp7720** [comment]
@Firedrake969  I get it, you dislike !e

**Comment by Firedrake969** [comment]
I don't dislike you as a person.
I, and others, dislike your attitude.

**Comment by robinp7720** [comment]
Yep. Bad idea ever asking to join any Scratch based community..
People are full of prejudice here :(

Forget my issues and this PR request

**Comment by Firedrake969** [comment]
It is with that attitude.

Bye then.

**Comment by MegaApuTurkUltra** [comment]
@robinp7720 Your refactor and clean up is great except for one thing: you formatted library code which should have stayed minified. Just make sure to format only non-library code and we could accept your PR.

And yes, a lot of the code is messy and everything. Classes might be nice but using classes in PHP is kind of annoying.

> I also am the only experienced php programmer here (As far as I can tell). You want me, trust me.

Let's not jump to conclusions. Remember that you're trying to make a case for why your PR should be accepted. Don't assume that we want your code really badly or anything, because we don't.

**Comment by Firedrake969** [comment]
thx

**Pull request closed without merging**
